# Generated by Django 5.1.7 on 2025-03-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_menu', '0003_cart_product_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
