# Generated by Django 5.1.7 on 2025-05-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_menu', '0005_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
